### PR TITLE
[BUG] IsPayToColdStaking tries to parse empty rawTX with Trezor api

### LINKED ISSUE #8: Support sending PIVX balance from TREZOR Model T
I understand this tool is intended for Ledger however currently it already also supports connecting, scanning & sending PIV rewards and displaying PIVX balance from TREZOR Model T.

Now Zephyr wallet has been abandoned and servers are offline TREZOR users PIVX balances are stuck without a working compatible Trezor / Pivx client.

Please add support for sending entire PIVX balance from TREZOR (and Ledger) to an external destination address.

### PR DESCRIPTION
**Pull request by random-zebra**
Closes #8

### CODE REVIEW

**Comment by jp-solutionz** [comment]
Currently testing Win 10 produces the following error:
C:\Users\JP\Downloads\PET4L-202011_fix-IsPayToColdStaking-trezor\PET4L-202011_fix-IsPayToColdStaking-trezor>pet4l.py
Traceback (most recent call last):
  File "C:\Users\JP\Downloads\PET4L-202011_fix-IsPayToColdStaking-trezor\PET4L-202011_fix-IsPayToColdStaking-trezor\pet4l.py", line 31, in <module>
    from mainApp import App
  File "C:\Users\JP\Downloads\PET4L-202011_fix-IsPayToColdStaking-trezor\PET4L-202011_fix-IsPayToColdStaking-trezor\src\mainApp.py", line 17, in <module>
    from mainWindow import MainWindow
  File "C:\Users\JP\Downloads\PET4L-202011_fix-IsPayToColdStaking-trezor\PET4L-202011_fix-IsPayToColdStaking-trezor\src\mainWindow.py", line 20, in <module>
    from hwdevice import HWdevice
  File "C:\Users\JP\Downloads\PET4L-202011_fix-IsPayToColdStaking-trezor\PET4L-202011_fix-IsPayToColdStaking-trezor\src\hwdevice.py", line 15, in <module>
    from trezorClient import TrezorApi
  File "C:\Users\JP\Downloads\PET4L-202011_fix-IsPayToColdStaking-trezor\PET4L-202011_fix-IsPayToColdStaking-trezor\src\trezorClient.py", line 13, in <module>
    from trezorlib import btc, exceptions, messages as trezor_proto, coins
ImportError: cannot import name 'coins' from 'trezorlib' (C:\Users\JP\AppData\Local\Programs\Python\Python39-32\lib\site-packages\trezorlib\__init__.py)

**Comment by random-zebra** [comment]
This is probably caused by a recent change in trezorlib.
Please check that your version is not higher than `v0.11.1` (will set it as maximum version in `requirements.txt`).

**Comment by jp-solutionz** [comment]
Okay the application now launches  (python 3.9) after running "pip install trezor==0.11.1" (installed version was 0.12.2) however does not connect to any servers.

Also attempted downgrading to python 3.8 and following packages with same result:
python-bitcoinrpc==1.0
bitcoin==1.1.42
btchip-python==0.1.27
trezor==0.11.1
PyQt5==5.14.0
requests==2.18.4
simplejson==3.17.2
ecdsa==0.16.0

The latest binary connects ok and I've disabled firewall etc and however I can't get either this branch or "master branch" or "2019_cold_staking_ledger" to connect so possibly something wrong with my config.

[PET4L_Logs_2020-11-12_07-55-40.txt](https://github.com/PIVX-Project/PET4L/files/5529019/PET4L_Logs_2020-11-12_07-55-40.txt)

**Comment by jp-solutionz** [comment]
I've also tried the "PyQt-5.9" release on Python 3.7.0 with the same result: 

https://github.com/PIVX-Project/PET4L/archive/v0.1.0-c.zip
python-bitcoinrpc==1.0
bitcoin==1.1.42
btchip-python==0.1.27
trezor==0.11.1
PyQt5==5.9.0
requests==2.18.4
simplejson==3.17.2
ecdsa==0.16.0

The wallet is able to check for new version and prompt for update so network stack seems fine however errors connecting to RPC server so perhaps there another dependency issue (binary version connects fine to same servers).

2020-11-12 18:52:07 : Checking PET4L version...
===> Remote version: 0.1.1
2020-11-12 18:52:13 : Trying to connect to RPC https://amsterdam.randomzebra.party:8080...
2020-11-12 18:52:15 : Connection to RPC server failed.
EXCEPTION
caller : run
function : updateRPCstatus
err: [WinError 10061] No connection could be made because the target machine actively refused it
===> Exception in RPC client
EXCEPTION
caller : run
function : updateRPCstatus
err: cannot unpack non-iterable NoneType object
===> exception updating RPC status:

[PET4L_Logs_2020-11-12_18-52-56.txt](https://github.com/PIVX-Project/PET4L/files/5532649/PET4L_Logs_2020-11-12_18-52-56.txt)

**Comment by random-zebra** [comment]
Mhm quite strange. Maybe an issue with either `httplib` or `ssl` modules (though they should be shipped already with python).

Anyway... I tested this with Trezor Model T on a Windows VM, and it works here. 

I've built binaries and uploaded them here for testing:
<https://github.com/PIVX-Project/PET4L/releases/tag/v0.1.1-a-PR9>

**Comment by jp-solutionz** [comment]
Great work @random-zebra !

I've tested the binary and was able to send the full balance from address #1 to address #2.

I'll also test on the original wallet and report back if any issues. Thanks for your help!

**Comment by random-zebra** [comment]
Glad it worked! Cheers :tumbler_glass:

**Comment by jp-solutionz** [comment]
Just tested the binary with Ledger Nano S and address 0 is correct however subsequent addresses differ from Ledger Live so any balances in change addresses previously used by Ledger Live transactions are not displayed.

This may be due to Ledger Live using path m/44'/77'/0' as opposed to Trezor etc which uses m/44'/119'/0'.

Perhaps an option is needed to select the correct path.

**Comment by random-zebra** [comment]
@jp-solutionz have you switched `internal/external` to `1` for change addresses?

**Pull request merged**
